### ISSUE TITLE
Docker images compatibility

### ISSUE THREAD

**Issue by kng** [jketterl/codecserver#13]
I'm testing both openwebrx:latest and :stable, neither of these seems to work with codecserver:latest, the :0.0.2 works on both.
I didn't find any info on this so found out by experimentation.

**Comment by jketterl** [comment]
That's because codecserver does not negotiate protocol in any way other than checking the version string, it must be identical.

`openwebrx:latest` and `:stable` currently both contain codecserver version 0.2.0 - the :latest hasn't been switched back to a dev version simply because there isn't any relevant changes between that and the development version.

`codecserver:stable` contains version 0.2.0 which works.

`codecserver:latest` contains version 0.3.0-dev which is not compatible.
